/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module up_down_counter(clk, reset, up_down, counter);
  wire [7:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  input clk;
  output [7:0] counter;
  wire [7:0] counter_up_down;
  input reset;
  input up_down;
  sky130_fd_sc_hd__clkinv_1 _27_ (
    .A(reset),
    .Y(_08_)
  );
  sky130_fd_sc_hd__clkinv_1 _28_ (
    .A(counter_up_down[0]),
    .Y(_00_[0])
  );
  sky130_fd_sc_hd__nor2_1 _29_ (
    .A(counter_up_down[0]),
    .B(counter_up_down[1]),
    .Y(_09_)
  );
  sky130_fd_sc_hd__or3b_1 _30_ (
    .A(counter_up_down[0]),
    .B(counter_up_down[1]),
    .C_N(up_down),
    .X(_10_)
  );
  sky130_fd_sc_hd__and3b_1 _31_ (
    .A_N(up_down),
    .B(counter_up_down[0]),
    .C(counter_up_down[1]),
    .X(_11_)
  );
  sky130_fd_sc_hd__a21boi_0 _32_ (
    .A1(counter_up_down[0]),
    .A2(counter_up_down[1]),
    .B1_N(up_down),
    .Y(_12_)
  );
  sky130_fd_sc_hd__o31ai_1 _33_ (
    .A1(_09_),
    .A2(_11_),
    .A3(_12_),
    .B1(_10_),
    .Y(_00_[1])
  );
  sky130_fd_sc_hd__a21oi_1 _34_ (
    .A1(up_down),
    .A2(_09_),
    .B1(_11_),
    .Y(_13_)
  );
  sky130_fd_sc_hd__xnor2_1 _35_ (
    .A(counter_up_down[2]),
    .B(_13_),
    .Y(_00_[2])
  );
  sky130_fd_sc_hd__nand2_1 _36_ (
    .A(counter_up_down[2]),
    .B(_11_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__o21ai_0 _37_ (
    .A1(counter_up_down[2]),
    .A2(_10_),
    .B1(_14_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__xor2_1 _38_ (
    .A(counter_up_down[3]),
    .B(_15_),
    .X(_00_[3])
  );
  sky130_fd_sc_hd__and2_0 _39_ (
    .A(counter_up_down[2]),
    .B(counter_up_down[3]),
    .X(_16_)
  );
  sky130_fd_sc_hd__nand2_1 _40_ (
    .A(_11_),
    .B(_16_),
    .Y(_17_)
  );
  sky130_fd_sc_hd__nor2_1 _41_ (
    .A(counter_up_down[2]),
    .B(counter_up_down[3]),
    .Y(_18_)
  );
  sky130_fd_sc_hd__o31ai_1 _42_ (
    .A1(counter_up_down[2]),
    .A2(counter_up_down[3]),
    .A3(_10_),
    .B1(_17_),
    .Y(_19_)
  );
  sky130_fd_sc_hd__nor4_1 _43_ (
    .A(counter_up_down[2]),
    .B(counter_up_down[3]),
    .C(counter_up_down[4]),
    .D(_10_),
    .Y(_20_)
  );
  sky130_fd_sc_hd__xor2_1 _44_ (
    .A(counter_up_down[4]),
    .B(_19_),
    .X(_00_[4])
  );
  sky130_fd_sc_hd__and4_1 _45_ (
    .A(counter_up_down[4]),
    .B(counter_up_down[5]),
    .C(_11_),
    .D(_16_),
    .X(_21_)
  );
  sky130_fd_sc_hd__nor4b_1 _46_ (
    .A(counter_up_down[4]),
    .B(counter_up_down[5]),
    .C(_10_),
    .D_N(_18_),
    .Y(_22_)
  );
  sky130_fd_sc_hd__a31oi_1 _47_ (
    .A1(counter_up_down[4]),
    .A2(_11_),
    .A3(_16_),
    .B1(_20_),
    .Y(_23_)
  );
  sky130_fd_sc_hd__xnor2_1 _48_ (
    .A(counter_up_down[5]),
    .B(_23_),
    .Y(_00_[5])
  );
  sky130_fd_sc_hd__nor2_1 _49_ (
    .A(_21_),
    .B(_22_),
    .Y(_24_)
  );
  sky130_fd_sc_hd__xnor2_1 _50_ (
    .A(counter_up_down[6]),
    .B(_24_),
    .Y(_00_[6])
  );
  sky130_fd_sc_hd__xor2_1 _51_ (
    .A(up_down),
    .B(counter_up_down[6]),
    .X(_25_)
  );
  sky130_fd_sc_hd__o21ai_0 _52_ (
    .A1(_21_),
    .A2(_22_),
    .B1(_25_),
    .Y(_26_)
  );
  sky130_fd_sc_hd__xnor2_1 _53_ (
    .A(counter_up_down[7]),
    .B(_26_),
    .Y(_00_[7])
  );
  sky130_fd_sc_hd__clkinv_1 _54_ (
    .A(reset),
    .Y(_01_)
  );
  sky130_fd_sc_hd__clkinv_1 _55_ (
    .A(reset),
    .Y(_02_)
  );
  sky130_fd_sc_hd__clkinv_1 _56_ (
    .A(reset),
    .Y(_03_)
  );
  sky130_fd_sc_hd__clkinv_1 _57_ (
    .A(reset),
    .Y(_04_)
  );
  sky130_fd_sc_hd__clkinv_1 _58_ (
    .A(reset),
    .Y(_05_)
  );
  sky130_fd_sc_hd__clkinv_1 _59_ (
    .A(reset),
    .Y(_06_)
  );
  sky130_fd_sc_hd__clkinv_1 _60_ (
    .A(reset),
    .Y(_07_)
  );
  sky130_fd_sc_hd__dfrtp_1 _61_ (
    .CLK(clk),
    .D(_00_[0]),
    .Q(counter_up_down[0]),
    .RESET_B(_01_)
  );
  sky130_fd_sc_hd__dfrtp_1 _62_ (
    .CLK(clk),
    .D(_00_[1]),
    .Q(counter_up_down[1]),
    .RESET_B(_02_)
  );
  sky130_fd_sc_hd__dfrtp_1 _63_ (
    .CLK(clk),
    .D(_00_[2]),
    .Q(counter_up_down[2]),
    .RESET_B(_03_)
  );
  sky130_fd_sc_hd__dfrtp_1 _64_ (
    .CLK(clk),
    .D(_00_[3]),
    .Q(counter_up_down[3]),
    .RESET_B(_04_)
  );
  sky130_fd_sc_hd__dfrtp_1 _65_ (
    .CLK(clk),
    .D(_00_[4]),
    .Q(counter_up_down[4]),
    .RESET_B(_05_)
  );
  sky130_fd_sc_hd__dfrtp_1 _66_ (
    .CLK(clk),
    .D(_00_[5]),
    .Q(counter_up_down[5]),
    .RESET_B(_06_)
  );
  sky130_fd_sc_hd__dfrtp_1 _67_ (
    .CLK(clk),
    .D(_00_[6]),
    .Q(counter_up_down[6]),
    .RESET_B(_07_)
  );
  sky130_fd_sc_hd__dfrtp_1 _68_ (
    .CLK(clk),
    .D(_00_[7]),
    .Q(counter_up_down[7]),
    .RESET_B(_08_)
  );
  assign counter = counter_up_down;
endmodule
